baseURL = "https://example.com"
title = "Xoz Techs | Blog"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Ala Eddine Benhassir"
    badge = "green"
    quote = "black"
    index_posts_num = 5
    google_search = true
    logo = "//xoztechs.com/static/img/logo.png"
    bio = """
    <p> U just Joined  A Cyber Corner , Welcom </p>
    <br />
    <p> This is about IT , Security  </p>
    """
    copyright = "Copyright Xoz techs © 2020, Powred by <a href='#'>Hugo</a> an opensource software ; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[[menu.icon]]
    url = "https://github.com/username/"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/username"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/username/"
    name = "youtube"
    weight = 1
